### ISSUE TITLE
Getting cursor via the script

### ISSUE THREAD

**Issue by michaelsomerville** [J7mbo/twitter-api-php#157] opened 2015-10-04 22:39 UTC
Hey, I don't know I am basic today or not .. lol

I have been trying to figure out a "GET MORE" call to get the rest of the cursor calls. Have you coded anything that works or used anything ? Thanks.

Note: i am using this script.

**Comment by J7mbo** [comment] 2015-10-05 09:01
Hey, I'm not sure what you mean by "GET MORE" calls... could you please provide a basic example of your code that shows where the problem is?

**Comment by michaelsomerville** [comment] 2015-10-05 21:02
I actually have 2 issues, thinking I am going lost in code these days. Lol.
1. Using your script to get the cursor and pull more data.
2. Also, I can't seem to get the code to export to CSV. 

There is limited information online about the API, I have been using FB Api for years and can't work wonders that. Now, with Twitter - we're trying to build a export of "IDS" for advertising and can't seem to get. lol

**Comment by J7mbo** [comment] 2015-10-09 09:59
Could you please provide a basic example of the code you have written that shows exactly what isn't working? Then I can take that away, put it in a test, and try and get it working.

**Comment by J7mbo** [comment] 2016-07-25 18:01
Closing due to lack of answer.

**Closed by J7mbo** 2016-07-25 18:01 UTC
